version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t docker-app -f docker/Dockerfile .
            docker save docker-app > docker-app.tar
      - persist_to_workspace:
          root: .
          paths:
            - docker-app.tar

  test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load Docker Image
          command: docker load < docker-app.tar
      - run:
          name: Docker Container Health Check
          command: |
            docker run -d --name test-container docker-app
            sleep 5
            docker ps | grep test-container
            docker logs test-container
            docker rm -f test-container

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load Docker Image
          command: docker load < docker-app.tar
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u sai102 --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker tag docker-app sai102/docker-app:latest
            docker push sai102/docker-app:latest

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
